### ISSUE TITLE
pub2TEI

### ISSUE THREAD

**Issue by jameshowison** [howisonlab/screenit-softcite#2]
From @kermitt2 in #1 

> Not related: the harvester download PDF and JATS XML files. After harvesting, you can transform all the JATS files into TEI files in the data path via:
> 
> nlm2tei = Nlm2tei(config_path=config_path)
> nlm2tei.process()
> 
> See https://github.com/kermitt2/article_dataset_builder#converting-the-pmc-xml-jats-files-into-xml-tei
> 
> Sending TEI files to the software mention recognizer is much faster than sending JATS files, which requires a transformation of the individual files - it's taking 2 seconds to load the XSLT. Transforming the JATS files in batch loads only the XSLT file one time for all. But for 1500 files, the runtime is not so crucial.

**Comment by jameshowison** [comment]
I tried this, but ran into trouble installing the https://github.com/kermitt2/Pub2TEI . Do I have it right that this can't be installed via pip, but needs to be done with a clone to disk?

And it requires an xml 2.0 processor.  I researched that a little, do you know any that can be installed via apt?  I'm trying with this one: https://manpages.ubuntu.com/manpages/trusty/man1/saxonb-xslt.1.html

**Comment by kermitt2** [comment]
> I tried this, but ran into trouble installing the https://github.com/kermitt2/Pub2TEI . Do I have it right that this can't be installed via pip, but needs to be done with a clone to disk?

just  clone on the disk, it's just static stuff
> git clone https://github.com/kermitt2/Pub2TEI 

Indicate the install path of Pub2TEI in the configuration file.

> And it requires an xml 2.0 processor. I researched that a little, do you know any that can be installed via apt? I'm trying with this one: https://manpages.ubuntu.com/manpages/trusty/man1/saxonb-xslt.1.html

Pub2TEI comes with an xml 2.0 processor under `Pub2TEI/Samples/saxon9he.jar` - so you just need a JRE installed. The python class Nlm2tei is using this saxon9he.jar as an external process, no additional xslt 2.0 processor to install.

**Comment by jameshowison** [comment]
This is working for me now.
