### ISSUE TITLE
Issue processing using client

### ISSUE THREAD

**Issue by jameshowison** [howisonlab/screenit-softcite#3]
I'm pushing ahead without the conversion to TEI XML, but I'm running into this issue (perhaps related to #1 as it also seems to be lmdb?)

```
client = software_mentions_client(config_path="config/config-client.json")
client.annotate_collection("./data", force=True)
```

Is giving me:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[10], line 2
      1 client = software_mentions_client(config_path="config/config-client.json")
----> 2 client.annotate_collection("./data", force=True)

File /srv/conda/envs/notebook/lib/python3.10/site-packages/software_mentions_client/client.py:207, in software_mentions_client.annotate_collection(self, data_path, force)
    204 self.env = lmdb.open(envFilePath, map_size=map_size)
    206 with self.env.begin(write=True) as txn:
--> 207     nb_total = txn.stat()['entries']
    208 print("\nnumber of entries to process:", nb_total, "entries\n")
    210 # iterate over the entries in lmdb

TypeError: Transaction.stat() missing 1 required positional argument: 'db'
```

This is with config as in this repo.

**Comment by jameshowison** [comment]
Tagging @kermitt2 in case not monitoring this repo :)

**Comment by kermitt2** [comment]
There's apparently some version issues, at least with lmdb. In your app, I think you set the dependencies with apt.txt?  
Normally these harvester/softcite client packages use `lmdb==0.94`, but you can upgrade to `lmdb==1.4.1` for latest version (I think lmdb version 0.94 is not working anymore with python 3.10). 
Can you add this to get the latest versions:

```
article_dataset_builder==0.2.4
software_mentions_client==0.1.7
```

**Comment by jameshowison** [comment]
I'm trying that, but running into one of those depressing hells :)

I first used the lines you suggested.  Those install fine, but the error persists.  lmdb that is installed is 0.94

So then I thought maybe you meant install lmdb 1.4.1 but that creates an pip unresolveable issue.

```
The conflict is caused by:
    The user requested lmdb>=1.4.1
    article-dataset-builder 0.2.4 depends on lmdb==0.94
```

**Comment by kermitt2** [comment]
> So then I thought maybe you meant install lmdb 1.4.1 but that creates an pip unresolveable issue.

Ah indeed, we are in the python dependency marshlands. I would need to publish a new version of article-dataset-builder and software_mentions_client with upgraded lmdb dependency to 1.4.1. 

Before I do that, would you be able maybe to create an environment with python < 3.10 and keeping everyone to `lmdb==0.94`? I was using all these modules without issues with python 3.8 and 3.9 and `lmdb==0.94`.

**Comment by jameshowison** [comment]
Ah, got it, so it's the python 3.10 that's causing the underlying problem, forcing us up to lmdb 1.4.1.  Ok, I'll change that and try again :)

**Comment by jameshowison** [comment]
Ok, that seems to have worked!  I pinned Python to 3.9 and things are progressing :).
